version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  websocket:
    build: .
    command: php /var/www/html/socket/server.php
    ports:
      - "8081:8080"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/002-seed.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    env_file:
      - .env

volumes:
  db_data:
