version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env

  websocket:
    build: .
    command: php /var/www/html/socket/server.php
    ports:
      - "8081:8080"
    volumes:
      - ./src:/var/www/html
